# -*- coding: utf-8 -*-
"""escola.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-BxMx-Fssb7575I0WwdJnVeza5bqyDII
"""

#1

import pandas as pd

dataframe = pd.read_csv('notas.csv')
dataframe

materia = dataframe[dataframe['Disciplina'] == 'Matematica']
materia
nota = materia[['Aluno','Disciplina' , 'Nota']]
nota.sort_values('Nota', ascending=False).head(1)

#2-a
materia = dataframe[dataframe['Disciplina'] == 'Historia']
materia
nota = materia[['Aluno','Disciplina' , 'Nota']]
nota.sort_values('Nota').head(1)

#2-b
materia = dataframe[dataframe['Disciplina'] == 'Historia']
materia
nota = materia[['Aluno','Disciplina' , 'Nota']]
nota.sort_values('Nota').head(10)

#3
media = dataframe.groupby('Aluno')['Nota'].mean()
media
# media = materia[['Aluno','Disciplina' , 'Nota']]
media.reset_index().sort_values('Nota', ascending=False).head(3)

#4
notasfisicaequimica = dataframe[(dataframe['Disciplina'] == 'Fisica') | (dataframe['Disciplina'] == 'Quimica')]
notasfisicaequimica
notasfisicaequimica = notasfisicaequimica.groupby('Aluno')['Nota'].mean()
notasfisicaequimica.reset_index().sort_values('Nota', ascending=False).head(1)

#5
pior_disciplina = dataframe.groupby('Disciplina')['Nota'].mean()
pior_disciplina
print(pior_disciplina.reset_index().sort_values('Nota'))
pior_disciplina.reset_index().sort_values('Nota').head(1)

#6
acima_ingles = dataframe[(dataframe['Disciplina'] == 'Ingles') & (dataframe['Nota']> 9)]
acima_ingles

#7
disciplinas = dataframe['Disciplina'].unique()
for disciplina in disciplinas:
    notass = dataframe[dataframe['Disciplina']== disciplina].sort_values(by='Nota', ascending=False)
    notass = notass.head(1)
    print(notass)